# MSDS Module 1 Practice 5

In [2]:
import numpy 
from numpy import *
from numpy.linalg import *

With numpy matrices, you can add, subtract, multiply, find the transpose find the inverse, solve systems of linear equations and much more.

Solve a system of consistent linear equations.  Refer to Lial Section 2.5 Example 7 Cryptography for the calculation

Right hand side of system of equations has data entered as a list and converted to 3x1 matrix and then a 1x3 matrix using the transpose function. Similar steps are taken for the matrix A.

In [3]:
rhs= [96, 87, 74]
rhs=matrix(rhs)
rhs=transpose(rhs)
print ('\nRight Hand Side of Equation')
print (rhs)

A =[[1, 3, 4], [2, 1, 3], [4, 2, 1]]
A= matrix(A)
print ('\nMatrix A')
print (A)


Right Hand Side of Equation
[[96]
 [87]
 [74]]

Matrix A
[[1 3 4]
 [2 1 3]
 [4 2 1]]


Numpy has various functions to perform matrix calculations.  The inverse function inv() is one of those.
__Inverse of A__

In [4]:
IA= inv(A)
IA

matrix([[-0.2,  0.2,  0.2],
        [ 0.4, -0.6,  0.2],
        [ 0. ,  0.4, -0.2]])

In what follows, I am converting matrices with floating point numbers  to matrices with integer numbers.  This is optional and being done to show that it is possible to do so with numpy matrices.

Note that the function dot() performs matrix multiplication. Verify inverse by multiplying matrix A and its inverse IA.

__Identity Matrix__

In [5]:
I= dot(IA,A)
I= int_(I)               # This converts floating point to integer.
I

matrix([[0, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

Solve the system of equations and convert to integer values. With numpy it is necessary to use dot() for the product.

__Solution to Problem__

In [6]:
result = dot(IA,rhs)
result = int_(result)    # This converts floating point to integer.
result

matrix([[12],
        [ 1],
        [20]])

__Illustration of solution with linalg.solve(,) function__

In [7]:
result2= linalg.solve(A,rhs)
int_(result2)   # This converts floating point to integer.

matrix([[13],
        [ 1],
        [20]])

Some square matrices do not have inverses. The following example shows how this is handled with numpy.  Note the magnitude of the elements.

__Example of an inverse matrix for inconsistent equations__

In [8]:
A= [[1,2,3],[-3,-2,-1], [-1,0,1]]
A= array(A)
IA= inv(A)
IA

array([[-3.37769972e+15, -3.37769972e+15,  6.75539944e+15],
       [ 6.75539944e+15,  6.75539944e+15, -1.35107989e+16],
       [-3.37769972e+15, -3.37769972e+15,  6.75539944e+15]])